language: csharp
solution: Mixer.Net.sln
git:
  depth: 1
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    mono: none
    dotnet: 1.0.0-preview2-003131
    env: DOTNETCORE=1
    
script:
  - sudo apt-get install dotnet-dev-1.0.1
  - dotnet restore
  - dotnet build --configuration Release --version-suffix beta-$TRAVIS_BUILDNUMBER

deploy:
  skip_cleanup: true
  provider: script
  script:
    - chmod +x deploy.sh
    - sudo deploy.sh
  on:
    branch: master